export const pageData = {
  pageTitel: "Guide: Buy property in Zanzibar",
  whitebannerText: "Find Your Perfect Slice of Paradise",
  btntext: "Explore properties",
  underImgText:
    "If you are considering buying property in Zanzibar, you have come to the right place. We will summarize everything you need to know to make an informed decision about purchasing real estate on the island Zanzibar. From understanding the buying process to navigating local regulations, we have got you covered. Read on to learn more.",
  titleOne: "Can foreigners own property in Zanzibar?",
  textOne:
    "Foreigners can own property in Zanzibar under certain conditions. The Tanzanian government allows foreign nationals to purchase and own property in the country, including Zanzibar, as long as they comply with the applicable laws and regulations. The process of purchasing property in Zanzibar as a foreigner involves several steps. Firstly, you will need to obtain a Residence Permit from the Immigration Department, which is required for any foreigner seeking to own property in the country. Additionally, you will need to secure a Land Alienation Certificate from the Ministry of Lands, Housing, and Human Settlements Development.Once you have obtained these necessary permits, you can then proceed with purchasing the property of your choice in Zanzibar. It is worth noting that there are restrictions on the type of land that foreigners can own in Zanzibar, and some areas may be restricted to Tanzanian nationals only. Overall, owning property in Zanzibar as a foreigner is possible with the appropriate permits and compliance with the applicable laws and regulations. If you are interested in owning property in Zanzibar contact us and we will help you with the whole process",
  titleTwo: "This is what you need to do to buy property in Zanzibar",
  textTwo:
    "If you considering buying property in Zanzibar as a foreigner, there are a few key things to keep in mind. While the process of purchasing real estate on the island is generally straightforward, there are some specific regulations and requirements that apply to non-residents.First and foremost, it is important to work with a reputable local real estate agent or lawyer who is familiar with the buying process and can guide you through the necessary steps. They can help you identify suitable properties, negotiate with sellers, and ensure that all legal requirements are met. As a foreigner, you will need to obtain a certificate of no objection from the Zanzibar Investment Promotion Authority (ZIPA) before purchasing any property. This certificate confirms that the property does not pose any security or other concerns, and is typically obtained through your lawyer or agent. Additionally, non-residents are generally required to pay a 5% stamp duty fee on the purchase price of the property. This fee is payable to the Zanzibar Revenue Board and is typically collected by the seller on behalf of the buyer. It is also important to note that non-residents are not permitted to own property in certain areas of Zanzibar, such as those designated for agricultural use or located near military installations. Your lawyer or agent can advise you on any specific restrictions that may apply to your desired property. Finally, it is a good idea to have a thorough understanding of the local real estate market and property values before making an offer on a property. This can help you ensure that you are getting a fair price and can also help you identify potential investment opportunities. In conclusion, buying property in Zanzibar as a foreigner involves some specific regulations and requirements. Working with a local real estate agent or lawyer, obtaining a certificate of no objection, paying stamp duty fees, and being aware of any restrictions on property ownership are all important factors to consider. With careful research and guidance, however, purchasing real estate in Zanzibar can be a rewarding investment opportunity."
};
