// Static catalog of Cocco Lagoon Resort & Spa (Pemba) apartment units.
// Cocco Lagoon has no public property API — data is sourced manually from https://invest.coccolagoon.com/

const IMG_BASE = "https://invest.coccolagoon.com/images/";

export const coccolagoonProperties = [
  {
    id: "studio-apartment",
    title: "Studio Apartment",
    badge: "AVAILABLE",
    tag: "Sea View",
    size: "35",
    rooms: 1,
    bathrooms: 1,
    price: "$125,999",
    roi: "~18% annual return",
    category: "Apartment",
    Area: "Pemba",
    Rent: "Sale",
    description:
      "A bright 35 m² studio apartment with sea views, finished turnkey and ready for rental income from day one as part of the Cocco Lagoon Resort & Spa condo-hotel program.",
    url: IMG_BASE + "studio-wizka-2c.jpg",
    imagesArray: [
      IMG_BASE + "studio-wizka-2c.jpg",
      IMG_BASE + "studio-wizka-3c.jpg",
      IMG_BASE + "studio-wizka-1c.jpg",
      IMG_BASE + "studio-extra-1c.jpg",
      IMG_BASE + "studio-extra-2c.jpg",
    ],
  },
  {
    id: "ocean-studio",
    title: "Ocean Studio",
    badge: "AVAILABLE",
    tag: "Sea View",
    size: "33",
    rooms: 1,
    bathrooms: 1,
    price: "$159,999",
    roi: "~18% annual return",
    category: "Apartment",
    Area: "Pemba",
    Rent: "Sale",
    description:
      "A compact 33 m² ocean-facing studio, finished turnkey, offering direct sea views and full-service hotel management within the Cocco Lagoon complex.",
    url: IMG_BASE + "ocean-studio-2c.jpg",
    imagesArray: [
      IMG_BASE + "ocean-studio-2c.jpg",
      IMG_BASE + "ocean-studio-3c.jpg",
      IMG_BASE + "ocean-studio-4c.jpg",
      IMG_BASE + "ocean-studio-5c.jpg",
    ],
  },
  {
    id: "beach-studio",
    title: "Beach Studio",
    badge: "AVAILABLE",
    tag: "Private Terrace",
    size: "54",
    rooms: 1,
    bathrooms: 1,
    price: "$249,914",
    roi: "~18% annual return",
    category: "Apartment",
    Area: "Pemba",
    Rent: "Sale",
    description:
      "A spacious 54 m² beach-front studio with a private terrace, finished turnkey, offering direct access to Cocco Lagoon's private beach.",
    url: IMG_BASE + "beach-studio-1c.jpg",
    imagesArray: [
      IMG_BASE + "beach-studio-1c.jpg",
      IMG_BASE + "beach-studio-2c.jpg",
      IMG_BASE + "beach-studio-3c.jpg",
    ],
  },
  {
    id: "2-bedroom-apartment",
    title: "2-Bedroom Apartment",
    badge: "BESTSELLER",
    tag: "Private Terrace",
    size: "72",
    rooms: 2,
    bathrooms: 1,
    price: "$217,999",
    roi: "~18% annual return",
    category: "Apartment",
    Area: "Pemba",
    Rent: "Sale",
    description:
      "Cocco Lagoon's bestselling unit — a 72 m² two-bedroom apartment with a private terrace, finished turnkey and managed by a professional hotel operator.",
    url: IMG_BASE + "2bedroom-wizka-2c.jpg",
    imagesArray: [
      IMG_BASE + "2bedroom-wizka-2c.jpg",
      IMG_BASE + "2bedroom-wizka-1c.jpg",
      IMG_BASE + "2bedroom-wizka-3c.jpg",
      IMG_BASE + "2bedroom-extra-1c.jpg",
      IMG_BASE + "2bedroom-extra-2c.jpg",
    ],
  },
  {
    id: "wille-waves",
    title: "Wille Waves",
    badge: "EXCLUSIVE",
    tag: "Private Pool",
    size: "110",
    rooms: 3,
    bathrooms: 2,
    price: "$299,999",
    roi: "~18% annual return",
    category: "Villa",
    Area: "Pemba",
    Rent: "Sale",
    description:
      "An exclusive 110 m² three-bedroom villa with a private pool, part of the Cocco Lagoon Resort & Spa masterplan on Pemba Island.",
    url: IMG_BASE + "waves-wizka-3c.jpg",
    imagesArray: [
      IMG_BASE + "waves-wizka-3c.jpg",
      IMG_BASE + "waves-wizka-2c.jpg",
      IMG_BASE + "waves-lux-1c.jpg",
      IMG_BASE + "waves-lux-2c.jpg",
      IMG_BASE + "waves-lux-3c.jpg",
    ],
  },
  {
    id: "sky-suite",
    title: "Sky Suite",
    badge: "EXCLUSIVE",
    tag: "Jacuzzi Terrace",
    size: "150",
    rooms: 1,
    bathrooms: 1,
    price: "$426,999",
    roi: "~18% annual return",
    category: "Apartment",
    Area: "Pemba",
    Rent: "Sale",
    description:
      "A 150 m² top-floor Sky Suite with a private jacuzzi terrace, offering panoramic ocean views over Cocco Lagoon Resort & Spa.",
    url: IMG_BASE + "sky-suite-1c.jpg",
    imagesArray: [
      IMG_BASE + "sky-suite-1c.jpg",
      IMG_BASE + "sky-suite-2c.jpg",
      IMG_BASE + "sky-suite-3c.jpg",
      IMG_BASE + "sky-suite-4c.jpg",
      IMG_BASE + "sky-suite-5c.jpg",
    ],
  },
  {
    id: "penthouse",
    title: "Penthouse",
    badge: "EXCLUSIVE",
    tag: "Jacuzzi Terrace",
    size: "230",
    rooms: 3,
    bathrooms: 3,
    price: "$789,000",
    roi: "~18% annual return",
    category: "Penthouse",
    Area: "Pemba",
    Rent: "Sale",
    description:
      "The flagship 230 m² Penthouse at Cocco Lagoon Resort & Spa, with a private jacuzzi terrace and panoramic views over the Indian Ocean.",
    url: IMG_BASE + "penthouse-1c.jpg",
    imagesArray: [
      IMG_BASE + "penthouse-1c.jpg",
      IMG_BASE + "penthouse-2c.jpg",
      IMG_BASE + "penthouse-3c.jpg",
      IMG_BASE + "penthouse-4c.jpg",
      IMG_BASE + "penthouse-5c.jpg",
    ],
  },
];

export const getCoccolagoonPropertyById = (id) =>
  coccolagoonProperties.find((p) => p.id === id) || null;
