import { AiOutlinePhone } from "react-icons/ai";
export const navlinks = [
  { id: 1, text: "Home", url: "./" },
  {
    id: 2,
    text: "Find Property",
    url: "../../public/images/propertyzanzibar",
  },
  {
    id: 3,
    text: "Sell Property",
    url: "/sellpropertyzanzibar",
  },
  {
    id: 4,
    text: "Rent Property",
    url: "/rentpropertyzanzibar",
  },
  {
    id: 5,
    text: "Rent Out House",
    url: "/rentouthousezanzibar",
  },
  {
    id: 6,
    text: "Rent House",
    url: "/renthousezanzibar",
  },
  {
    id: 7,
    text: "Buy House",
    url: "/buyhousezanzibar",
  },
  {
    id: 8,
    text: "Buy Land",
    url: "/buylandzanzibar",
  },
  {
    id: 9,
    text: "About Us",
    url: "/about",
  },
  {
    id: 10,
    text: "Contact Us",
    url: "/contact",
    icon: <AiOutlinePhone />,
  },
];
export const objects = [
  {
    id: 1,
    date: 2110,
    url: ["./images/object-1.jpg", "./images/object-2.jpg"],
    location: "Paje",
    price: 90,
    size: 1000,
    type: "House",
    to: "Buy",
    desc: "7 min to the beach",
    info: "Big house in Zanzibar for sell with 4 bedrooms, 3 bathrooms, big kitchen and 2 living rooms. The house is built this year and modern. The house have a big garden with lot of space.",
  },
  {
    id: 2,
    date: 2110,
    url: ["./images/object-2.jpg"],
    location: "Paje",
    price: 1000,
    size: 200,
    type: "House",
    to: "Rent",
    desc: "3 min to the beach",
    info: "Big house in Paje Zanzibar with 3 bedrooms, 2 bathrooms, big kitchen and 1 living rooms. The house is built this year and modern. The house have a big garden with lot of space.",
  },
  {
    id: 3,
    date: 2110,
    url: ["./images/object-3.jpg"],
    location: "Paje",
    price: 130,
    size: 2500,
    type: "Land",
    to: "Buy",
    desc: "Beach front plot",
    info: "Beach front plot in Paje Zanzibar with palms and other trees. Here yoou can build club, restaurant and bangalow , barhroomhouse and hotell. Located in were popular area with lot of thigs to do",
  },
  {
    id: 4,
    date: 2111,
    url: ["./images/plotzanzibar.jpg"],
    location: "Pemba",
    price: 55,
    size: 1200,
    type: "Land",
    to: "Buy",
    desc: "Beach front plot",
    info: "Beach front plot in Zanzibar Pemba with palms and other trees. Here yoou can build club, restaurant and bangalow or house. Located in were popular area with lot of thigs to do",
  },
  {
    id: 5,
    date: 2111,
    url: ["./images/beachhousezanzibar.jpg"],
    location: "Jambiani",
    price: 1200,
    size: 300,
    type: "House",
    to: "Rent",
    desc: "Beach front house",
    info: "Beach front house for rent in Jambiani Zanzibar with pool. 5 bedrooms, 2 living room, 3 bathrooms and a big kitchen",
  },
  {
    id: 6,
    date: 2112,
    url: ["./images/landpaje-1.jpg", "./images/my-2.jpg"],
    location: "Paje",
    price: 16,
    size: 1400,
    type: "Land",
    to: "Buy",
    desc: "5 min to the beach",
    info: "Big land in Paje Zanzibar and close to the main road. Close to the village and paje beach. Here you can build smaller houses for business or a big house with pool.",
  },
  {
    id: 7,
    date: 2112,
    url: [
      "./images/buylandpaje-3.jpg",
      "./images/uk.png",
      "./images/buylandpaje-2.jpg",
    ],
    location: "Paje",
    price: 13,
    size: 900,
    type: "Land",
    to: "Buy",
    desc: "5 min to the beach",
    info: "Big land in Paje Zanzibar and close to the main road. Close to the village and paje beach. Here you can build smaller houses for business or a big house with pool.",
  },
  {
    id: 8,
    date: 2112,
    url: [
      "./images/beachplotzanzibar.jpg",
      "./images/beachplotzanzibar-1.jpg",
      "./images/beachplotzanzibar-2.jpg",
    ],
    location: "Paje",
    price: 125,
    size: 4900,
    type: "Land",
    to: "Buy",
    desc: "Beach side plot",
    info: "Big land in Paje Zanzibar, 1min walk to the beach and close to the main road. Close to the village located at paje beach side. Here you can build hotell or resort,  houses for business or a 2- 3 big house with pool.",
  },

  {
    id: 9,
    date: 2112,
    url: ["./images/my-1.jpg", "./images/my-2.jpg"],
    location: "Paje",
    price: 8,
    size: 555,
    type: "Land",
    to: "Buy",
    desc: "5 min to the beach",
    info: "Nice plot in Paje Zanzibar and very close to the main road. The plot is 15 meter in width and 37 meter in length. Close to the village and paje beach. Here you can build 2 smaller houses for business or a bigger house with bigger garden.",
  },
  {
    id: 10,
    date: 2112,
    url: ["./images/mina3.JPG", "hh.png"],
    location: "Paje",
    price: 7,
    size: 1040,
    type: "Land",
    to: "Buy",
    desc: "7 min to the beach",
    info: "Land in Paje Zanzibar , area name Domo kuchu juu on the way to Jambiani only 2 min with car. Perfect for a house with big garden. The plot is located on the other side of the road to the beach. 3 min in the forest with car. There is lot of houses there and some under construction",
  },
  {
    id: 11,
    date: 2112,
    url: ["./images/mina3.JPG", "./images/hh.png"],
    location: "Paje",
    price: 11,
    size: 2000,
    type: "Land",
    to: "Buy",
    desc: "7 min to the beach",
    info: "Big land in Paje Zanzibar, area name Domo kuchu juu on the way to Jambiani only 2 min with car. Perfect for a house with big garden. The plot is located on the other side of the road to the beach. 3 min in the forest with car. There is lot of houses there and some under construction",
  },
];

export const bannerInfo = [
  {
    company: "Tripple M Limited",
    id: 1,
    name: "Ahmed Shawarma",
    url: ["../../public/images//buildhousezanzibar.jpg"],
  },
];
