export const faqdata = [
  {
    title: "How much does it cost?",
    text: "Looking to sell or rent out your property or business in Zanzibar? Look no further than our platform! We offer an affordable and effective way to reach potential buyers and renters in the region. For just $10 per ad, you can list your property or business and connect with a wider audience. Our platform is easy to use and there are no hidden fees or additional costs. You can rest assured that you're getting the best value for your money. Whether you're selling a house, renting out an apartment, or promoting your business in Zanzibar, our platform provides the perfect opportunity to reach the right people. With our platform, you can showcase your property or business with detailed descriptions, high-quality photos, and other essential details. Plus, our platform is optimized for search engines, so your listings have a greater chance of being discovered by potential buyers and renters. So why wait? Sign up today and start advertising your property or business in Zanzibar for just $10 per ad, with no hidden costs or fees."
  },
  {
    title: "How does it work?",
    text: "Looking for an easy and hassle-free way to sell or rent out your property or business in Zanzibar? Our platform makes it simple and straightforward to list your property or business for sale or rent. All you need to do is provide all the necessary information, upload high-quality photos, and add your contact details. Once you have completed these steps, you can pay for your ad and your listing will be live! Our platform is designed specifically for sellers and renters in Zanzibar. We understand the unique needs of our users in this region and we have optimized our platform to meet those needs. With our easy-to-use interface, you can list your property or business quickly and easily. With our platform, you can showcase your property or business in the best possible light. You can provide detailed descriptions of your property or business, highlight its unique features, and add high-quality photos that showcase its best angles. Plus, you can rest assured that your listing will be seen by potential buyers or renters in Zanzibar. So why wait? Sign up today and start selling or renting out your property or business in Zanzibar with ease. With our simple and straightforward process, you'll be up and running in no time, and your listing will be seen by potential buyers or renters in Zanzibar in no time."
  },
  {
    title: "How fast does it go?",
    text: "Looking for a fast and efficient way to sell or rent out your property or business in Zanzibar? Our platform offers a quick and easy solution for sellers and renters in the region.Our platform is designed with speed and efficiency in mind. We know that time is of the essence when it comes to selling or renting out your property or business, and we've streamlined our process to make it as fast as possible. With just a few clicks, you can list your property or business and have it seen by potential buyers or renters in Zanzibar. Our platform also offers a range of features to help you sell or rent out your property or business more quickly. For example, you can add high-quality photos and detailed descriptions to showcase your property or business in the best possible light. Plus, our platform is optimized for search engines, so your listing will be seen by more potential buyers or renters in Zanzibar. So if you're looking for a fast and efficient way to sell or rent out your property or business in Zanzibar, look no further than our platform. Sign up today and start listing your property or business, and you could be on your way to a successful sale or rental in no time!"
  }
];
